### ISSUE TITLE
Nox - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by hitnrun76** [rauenzi/Nox#8] opened 2019-06-19 16:40 UTC
Hi,
I have a little problem with the theme i can't see the microphone logo, the headset logo and the parameter logo to the bottom left corner :/

Have a good day ;)

**Comment by zerebos** [comment] 2019-06-19 17:04
Hi, this issue comes from a website I do not support and is a duplicate of #5

**Closed as completed by zerebos** 2019-06-19 17:04 UTC

**Comment by MasicoreLord** [comment] 2019-06-19 17:24
Wished there was a bot that would automatically close these kind of issue reports.
